# if a socket is not under a category it means it's simply rendered in the body of the node with no category dropdown
# color type is also compatible with vector and uv
Blur:
  out:
    Color: color # socket type
  in:
    Color: color # socket type
    Radius: slider:[0,100] # type:range
  src: web/static/nodes/operations/blur.js # the actual functionality of the node